const { requireAuth } = require("../_utils/requireAuth");
const { readDraft, writeDraft, hasDraft, DEFAULT_DATA } = require("../_utils/draft");

// ─── GitHub config (for fetching current published data) ──────────────────────

const GITHUB_PAT = process.env.GITHUB_PAT;
const REPO_OWNER = "morpheus-30";
const REPO_NAME = "ninja-portfolio";
const FILE_PATH = "src/data/portfolio.js";
const BRANCH = "main";

/**
 * Parse the published portfolio.js file content into a data object.
 * Uses Function constructor to safely evaluate the ES module exports.
 * This is safe because the file is always authored by us (either hand-written
 * or generated by generatePortfolioFile).
 */
function parsePortfolioFile(content) {
  try {
    // Convert ES module exports to variable assignments for evaluation
    const evalCode = content
      .replace(/export const /g, "const ")
      .replace(/\/\*[\s\S]*?\*\//g, ""); // strip block comments

    // Wrap in a function that returns the data
    const fn = new Function(`
      ${evalCode}
      return { profile, bio, skills, projects };
    `);

    const result = fn();

    if (result.profile && result.bio && result.skills && result.projects) {
      return result;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Fetch the current published portfolio data from GitHub.
 */
async function fetchPublishedData() {
  if (!GITHUB_PAT) return null;

  try {
    const response = await fetch(
      `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${FILE_PATH}?ref=${BRANCH}`,
      {
        headers: {
          Authorization: `Bearer ${GITHUB_PAT}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
      }
    );

    if (!response.ok) return null;

    const fileData = await response.json();
    const fileContent = Buffer.from(fileData.content, "base64").toString("utf-8");
    return parsePortfolioFile(fileContent);
  } catch {
    return null;
  }
}

// ─── Handler ──────────────────────────────────────────────────────────────────

module.exports = async function handler(req, res) {
  const user = requireAuth(req, res);
  if (!user) return;

  res.setHeader("Cache-Control", "no-store");

  if (req.method === "GET") {
    // If a local draft exists in /tmp, use it
    if (hasDraft()) {
      return res.status(200).json({
        data: readDraft(),
        hasDraft: true,
      });
    }

    // Otherwise, fetch the current published content from GitHub
    const published = await fetchPublishedData();
    if (published) {
      return res.status(200).json({
        data: published,
        hasDraft: false,
      });
    }

    // Fallback: use hardcoded defaults (only if GitHub fetch fails)
    return res.status(200).json({
      data: DEFAULT_DATA,
      hasDraft: false,
    });
  }

  if (req.method === "PUT") {
    try {
      const data = req.body;
      if (!data || typeof data !== "object") {
        return res.status(400).json({ error: "Invalid draft data." });
      }

      const requiredKeys = ["profile", "bio", "skills", "projects"];
      for (const key of requiredKeys) {
        if (!(key in data)) {
          return res.status(400).json({ error: `Missing required field: ${key}` });
        }
      }

      writeDraft(data);
      return res.status(200).json({ success: true });
    } catch (err) {
      return res.status(500).json({ error: "Failed to save draft." });
    }
  }

  if (req.method === "DELETE") {
    try {
      const fs = require("fs");
      const path = require("path");
      const draftPath = path.join("/tmp", "portfolio-draft.json");
      if (fs.existsSync(draftPath)) {
        fs.unlinkSync(draftPath);
      }
      return res.status(200).json({ success: true });
    } catch {
      return res.status(500).json({ error: "Failed to discard draft." });
    }
  }

  res.status(405).json({ error: "Method not allowed." });
};
